### ISSUE TITLE
Nested properties don't respect splits on `,`

### ISSUE THREAD

**Issue by mdekrey** [typestyle/typestyle#169]
When `$nest` is used, nested selectors containing `,` aren't split, such that rules specified after a comma are treated as new rules from root.

Encountered on v1.3.6.

## Steps to reproduce:

1. Create a simple rule with a nested selector including a comma:

        style({
            $nest: {
                "h1, h3": {
                    display: "block",
                },
            },
        })

2. Check output code.

## Actual:

    .fql7r6q h1, h3{display:block}

## Expected:

    .fgq58f6 h1, .fgq58f6 h3{display:block}

**Comment by mdekrey** [comment]
Workaround:

Use `&` to indicate additional selectors.

    style({
        $nest: {
            "& h1, & h3": {
                display: "block",
            },
        },
    })

**Comment by basarat** [comment]
> Use & to indicate additional selectors.

This is by design. We assume the selector is a child `.generate child` and do no magic parsing of `child`. For explicit control `&` should be used as documented : http://typestyle.io/#/core/concept-interpolation which is what you have already figured out as well :rose:

**Comment by whitecolor** [comment]
@basarat 

I use the following snippet to generate css:

```ts
style({
  $nest: {	
    '& .c1, & .c2': {      
      $nest: {
        '&:hover,&:active': {
          $nest: {
            '& .nested': {
              opacity: '0.15'
            }
          }
        },
      }
    },
  }
})
```
the generated css:
```css
.generated .c1, 
.generated .c2:hover,
.generated .c1, 
.generated .c2:active .nested {
    opacity:0.15 !important
}
```

What I need to get:

```css
.generated .c1:hover .nested, 
.generated .c1:active .nested, 
.generated .c2:hover .nested, 
.generated .c2:active .nested {
    opacity:0.15 !important
}
```
How should I modify my snippet to get what I want?
