### ISSUE TITLE
How to enforce "uniqueness" / separate outputs?

### ISSUE THREAD

**Issue by Frikki** [typestyle/typestyle#26]
* **typestyle v0.5.6**

I’ve encountered an issue that I don’t know how to solve.

```javascript
const MyStyle = style({
  color: 'blue',
  '&::-webkit-input-placeholder': {
    color: `rgba(0, 0, 0, 0)`
  },
  '&::-moz-placeholder': {
    color: `rgba(0, 0, 0, 0)`
  },
  '&::-ms-input-placeholder': {
    color: `rgba(0, 0, 0, 0)`
  }
}); // => f13byakl
```

This outputs the following styles:

```css
.f13byakl{color:blue}
.f13byakl::-webkit-input-placeholder,
.f13byakl::-moz-placeholder,
.f13byakl::-ms-input-placeholder{color:rgba(0, 0, 0, 0)}
```

The problem is, however, that browsers do not understand:

```css
.f13byak::-webkit-input-placeholder, /* WebKit fails here */
.f13byak::-moz-placeholder,          /* Firefox fails here */
.f13byak::-ms-input-placeholder {    /* IE fails here */
    color: rgba(0, 0, 0, 0);
}
```

To make this work,  the final CSS must look like this:

```css
.f13byak::-webkit-input-placeholder {
    color: rgba(0, 0, 0, 0);
}
.f13byak::-moz-placeholder {
    color: rgba(0, 0, 0, 0);
}
.f13byak::-ms-input-placeholder {
    color: rgba(0, 0, 0, 0);
}
```

How is it possible to enforce this output?

**Update** _Oct 31, 2016, 8:46 PM (CEST)_

As [suggested by Blake Embrey](https://github.com/blakeembrey/free-style/issues/39#issuecomment-257377640), we can use `registerRule(selector, object)` as a workaround until the issue has been solved.

In TypeStyle, this would be:

```javascript
cssRule(`.${className}::placeholder`, {})
```
