### ISSUE TITLE
Idea for loading .css files directly

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/typestyle#260]
I have been thinking about this for weeks, so let me see if I can get all of this idea out without it getting too hairy...  

Assume this css file is next to a React/Vue (or whatever) component:

```css
html, body {
    font-family: Arial;
    font-size: 14px;
    margin: 0;
    padding: 0;
}
* {
    box-sizing: border-box;
    position: relative;
}
.flex {
    display: flex;
}
.flex-fill {
    flex: 1 1 auto;
}
.flex-fixed {
    flex: 0 0 auto;
}
```

You would convert that to roughly this to bring it into TypeStyle:

```ts
import { cssRule, stylesheet } from 'typestyle';

cssRule('html, body', {
    font-family: Arial;
    font-size: 14px;
    margin: 0;
    padding: 0;
}) 

cssRule('*', {
    box-sizing: border-box;
    position: relative;
}) 

// or use a namespace
export const styles = stylesheet({
    flex: {
        display: 'flex'
    },
    flexFill {
        flex: '1 1 auto'
    }
    flexFixed {
        flex: '0 0 auto'
    }
})
```

What if we could use postcss and a Webpack loader to do that conversion at build time?  If that is possible, we could provide the option of using css files (perhaps a subset) and still leverage the power of TypeStyle at runtime/SSR.

```tsx
import { styles } from './component.css'; 

export function (props) {
    return (
        <div className={styles.flex}>
            <div className={styles.flexFixed}>Name<div>
            <div className={styles.flexFill}>Description<div>
        <div>
    )
}
```

The converter (https://typestyle.github.io/converter/) is doing something similar although the rules are much simpler.  I guess the question I have is... is there a way to provide TypeScript declarations for this and is this something we should create?

I think I would use it in some of my projects.
