### ISSUE TITLE
Delimited lists in properties

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/typestyle#27]
@basarat I think we should think about adding a helper that produces a delimited list.  The use case I am thinking about is backgroundImage.

My first choice for how to do this would be to use arrays, but those are already used for fallback values.

**Here is what I am thinking**
```ts
style({
  backgroundImage: list(linearGradient(/* */), url(/* */))
})
```

**would produce**
```css
.hashed-class {
    background-image: linear-gradient(/* */), url(/* */);
}
```

What do you think, and what other ways could we solve for this?
