### ISSUE TITLE
Interpolation question with deep $nest

### ISSUE THREAD

**Issue by whitecolor** [typestyle/typestyle#292]
I use the following typestyle snippet to generate CSS:

```ts
style({
  $nest: {	
    '& .c1, & .c2': {      
      $nest: {
        '&:hover,&:active': {
          $nest: {
            '& .nested': {
              opacity: '0.15'
            }
          }
        },
      }
    },
  }
})
```

The generated CSS:

```css
.generated .c1, 
.generated .c2:hover,
.generated .c1, 
.generated .c2:active .nested {
    opacity:0.15
}
```
What I need to get:

```css
.generated .c1:hover .nested, 
.generated .c1:active .nested, 
.generated .c2:hover .nested, 
.generated .c2:active .nested {
    opacity:0.15
}
```
How should I modify my snippet to get what I need?
