### ISSUE TITLE
Psuedoselector Order

### ISSUE THREAD

**Issue by thomas-jeepe** [typestyle/typestyle#47]
First off, love the library I really love the intellisense :)

But I am having a little bit of trouble getting something to work. Basically I'm trying to get an item with an active and hover property. Thing is because of the hashing, the active property comes before the hover and therefore doesn't work.

Here it is:

`Menu.tsx`

```javascript
const background = '#FFEE58'
  const hoverBackground = '#FFF59D'
  const activeBackground = 'white'

  export const wrapper = style({
    background,
    borderRadius: '.3em',
    // boxShadow: '0 .2em .5em rgba(0,0,0,0.25)',
    padding: '.1em',
    // userSelect: 'none',
    width: '13em',
    outline: 'none',
  })
  export const item = style({
    background,
    borderRadius: '.3em',
    borderTop: `1px solid ${hoverBackground}`,
    cursor: 'pointer',
    display: 'flex',
    fontSize: '1.3em',
    padding: '.8em 2.1em .8em 2.1em',
    fontFamily: 'Verdana',
    nested: {
      '&:first-child': {
        borderTop: 'none',
      },
     // IMPORTANT PART
      '&:hover': {
        background: hoverBackground,
      },
      '&:active': {
        background: activeBackground,
      },
    },
  })
```

`FlatButton.tsx`

```javascript
const background = '#FFEE58'
  const hoverBackground = '#FFF59D'
  const activeBackground = '#FFF9C4'
  export const button = style({
    background,
    border: 'none',
    borderRadius: '1em',
    cursor: 'pointer',
    fontSize: '1.3em',
    outline: 'none',
    padding: '.3em .8em .3em .8em',
    nested: {
     // IMPORTANT PART
      '&:hover': { background: hoverBackground, },
      '&:active': { background: activeBackground, },
    },
  })
```

Style tag at the top of the page

```css
.fesaj7k{background:#FFEE58;border:none;border-radius:1em;cursor:pointer;font-size:1.3em;outline:none;padding:.3em .8em .3em .8em}.fesaj7k:active{background:#FFF9C4}.f18voftf{background:#FFEE58;border-radius:.3em;outline:none;padding:.1em;width:13em}.fg568yj{background:#FFEE58;border-radius:.3em;border-top:1px solid #FFF59D;cursor:pointer;display:flex;font-family:Verdana;font-size:1.3em;padding:.8em 2.1em .8em 2.1em}.fg568yj:first-child{border-top:none}.fg568yj:active{background:white}.fesaj7k:hover,.fg568yj:hover,.f1r5fwfw{background:#FFF59D}.f6rmpxq{background:#FFCA28;height:64px}
```

My best guess is that the hashing sees that the hover psuedo selector style is the same as another style, which comes later, so it puts it at the end.

I changed the hover background on the item to purple (no duplicate style any where else) and active worked perfectly, here is the css:

```css
.fesaj7k{background:#FFEE58;border:none;border-radius:1em;cursor:pointer;font-size:1.3em;outline:none;padding:.3em .8em .3em .8em}.fesaj7k:active{background:#FFF9C4}.f18voftf{background:#FFEE58;border-radius:.3em;outline:none;padding:.1em;width:13em}.f1tgg7o8{background:#FFEE58;border-radius:.3em;border-top:1px solid #FFF59D;cursor:pointer;display:flex;font-family:Verdana;font-size:1.3em;padding:.8em 2.1em .8em 2.1em}.f1tgg7o8:first-child{border-top:none}.f1tgg7o8:hover{background:purple}.f1tgg7o8:active{background:white}.fesaj7k:hover,.f1r5fwfw{background:#FFF59D}.f6rmpxq{background:#FFCA28;height:64px}
```

As you can see, `.f1tgg7o8:hover` comes before `.f1tgg7o8:active` so it works properly.

Version of typestyle: 0.12.5

Also, you seem to be missing the css properties `boxShadow` and `userSelect` for your `CSSProperties` interface.
