### ISSUE TITLE
Handling descendants states

### ISSUE THREAD

**Issue by sporto** [typestyle/typestyle#8]
This is a common scenario for us: User hovers on an element and a child element needs to change. You would do this in plain css as:

```css
.button:hover .label {
	colour: red;
}
```

I'm wondering if typestyles has a solution for this?

Also see https://github.com/Khan/aphrodite/issues/10
